language: node_js
node_js:
- lts/*
install:
- yarn install
script:
- yarn build
branch:
  only:
    - master
addons:
  ssh_known_hosts:
  - 47.94.92.217
cache:
  directories:
    - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
after_success:
- ssh travis@47.94.92.217 -o StrictHostKeyChecking=no 'cd ~/new-blog && git pull && yarn install && yarn build'